api_platform:
    title: The v4 API
    version: 4.0.0
    show_webby: false
    collection:
        order: 'DESC'
    openapi:
        contact:
            name: Fundación Platoniq
            url: http://platoniq.net/contact/
            email: contacto@platoniq.net
        termsOfService:
        license:
            name: AGPL
            url: https://www.gnu.org/licenses/agpl-3.0.txt
        swagger_ui_extra_configuration:
            filter: true
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        csv: ['text/csv']
    docs_formats:
        html: ['text/html']
        json: ['application/json']
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
    use_symfony_listeners: true
    swagger:
        api_keys:
            access_token:
                name: Authorization
                type: header
