services:
  php:
    build: docker/php
    container_name: goteo-v4-php
    volumes:
      - .:/app
      - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro

  nginx:
    image: nginx:alpine
    container_name: goteo-v4-nginx
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_HTTP_PORT:-8090}:80"
      - "${APP_HTTPS_PORT:-8091}:433"

  mariadb:
    image: mariadb:10.11.2
    container_name: goteo-v4-mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-goteo}
      MYSQL_PASSWORD: ${DB_PASSWORD:-goteo}
      MYSQL_DATABASE: ${DB_DATABASE:-goteo}
      MYSQL_USER: ${DB_USER:-goteo}

volumes:
  mariadb-data: