version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    container_name: goteo-v4-php
    volumes:
      - .:/app
      - ./docker/php/conf.d/apc.ini:/usr/local/etc/php/conf.d/apc.ini:ro
      - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    env_file: ".env.local"
    ports:
      - "9000:9000"
      - "9003:9003"

  nginx:
    image: nginx:alpine
    container_name: goteo-v4-nginx
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_HTTP_PORT:-8090}:80"
      - "${APP_HTTPS_PORT:-8091}:443"
    depends_on:
      - php

  mariadb:
    image: mariadb:10.11.2
    container_name: goteo-v4-mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-goteo}
      MYSQL_PASSWORD: ${DB_PASSWORD:-goteo}
      MYSQL_DATABASE: ${DB_DATABASE:-goteo}
      MYSQL_USER: ${DB_USER:-goteo}

volumes:
  mariadb-data:
