<?php

namespace App\Entity;

use ApiPlatform\Metadata as API;
use App\Repository\TransactionOriginRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TransactionOriginRepository::class)]
class TransactionOrigin
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[API\ApiProperty(readable: false)]
    private ?int $id = null;

    #[ORM\OneToOne(mappedBy: 'target', cascade: ['persist', 'remove'])]
    #[API\ApiProperty(writable: false, readable: false)]
    private ?Transaction $transaction = null;

    /**
     * The Accounting asked to originate the Transaction amount.
     */
    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank()]
    private ?Accounting $accounting = null;

    /**
     * The Accounting Outgoing movement generated by this Transaction.
     */
    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    #[API\ApiProperty(writable: false)]
    private ?AccountingOutgoing $outgoing = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTransaction(): ?Transaction
    {
        return $this->transaction;
    }

    public function setTransaction(Transaction $transaction): static
    {
        // set the owning side of the relation if necessary
        if ($transaction->getOrigin() !== $this) {
            $transaction->setOrigin($this);
        }

        $this->transaction = $transaction;

        return $this;
    }

    public function getAccounting(): ?Accounting
    {
        return $this->accounting;
    }

    public function setAccounting(?Accounting $accounting): static
    {
        $this->accounting = $accounting;

        return $this;
    }

    public function getOutgoing(): ?AccountingOutgoing
    {
        return $this->outgoing;
    }

    public function setOutgoing(AccountingOutgoing $outgoing): static
    {
        $this->outgoing = $outgoing;

        return $this;
    }
}
