# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Gateway\GatewayInterface:
            tags: ['app.gateway.gateway']
        App\Library\Benzina\Pump\PumpInterface:
            tags: ['app.lib.benzina.pump.pump']
        App\Library\Economy\Currency\ExchangeInterface:
            tags: ['app.lib.economy.currency.exchange']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\DependencyInjection\SystemVariablesLoader:
        tags: ['container.env_var_loader']

    App\OpenApi\OpenApiFactory:
        autoconfigure: false
        decorates: 'api_platform.openapi.factory'
        arguments:
            - '@App\OpenApi\OpenApiFactory.inner'

    App\Gateway\GatewayLocator:
        arguments:
            - !tagged 'app.gateway.gateway'

    App\Gateway\Paypal\PaypalService:
        arguments:
            - '%env(PAYPAL_API_ADDRESS)%'
            - '%env(PAYPAL_CLIENT_ID)%'
            - '%env(PAYPAL_CLIENT_SECRET)%'
            - '%env(PAYPAL_WEBHOOK_ID)%'

    App\Gateway\Stripe\StripeGateway:
        arguments:
            - '%env(STRIPE_API_KEY)%'
            - '%env(STRIPE_WEBHOOK_SECRET)%'

    App\Service\Auth\AuthService:
        arguments:
            - '%env(APP_SECRET)%'

    App\Library\Benzina\Benzina:
        arguments:
            - !tagged 'app.lib.benzina.pump.pump'

    App\Library\Economy\Currency\ExchangeLocator:
        arguments:
            - !tagged 'app.lib.economy.currency.exchange'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
