name: PHP CS Fixer

on: [pull_request]

env:
  PHP_VERSION: '8.3'
  PHP_EXTENSIONS: pdo_mysql

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          php_extensions: ${{ env.PHP_EXTENSIONS }}

      - name: PHP CS Fixer
        run: php-cs-fixer check
